#pragma once
#include"Struct.h"
extern FILTER_SET_OPTIONS FilterSetOptions;
extern FILTER_SET_MODULE_OPTIONS FilterSetModuleOptions;
extern FILTER_ATTACH FilterAttach;
extern FILTER_DETACH FilterDetach;
extern FILTER_RESTART FilterRestart;
extern FILTER_PAUSE FilterPause;
extern FILTER_SEND_NET_BUFFER_LISTS FilterSendNetBufferLists;
extern FILTER_SEND_NET_BUFFER_LISTS_COMPLETE FilterSendNetBufferListsComplete;
extern FILTER_CANCEL_SEND_NET_BUFFER_LISTS FilterCancelSendNetBufferLists;
extern FILTER_RECEIVE_NET_BUFFER_LISTS FilterReceiveNetBufferLists;
extern FILTER_RETURN_NET_BUFFER_LISTS FilterReturnNetBufferLists;
extern FILTER_NET_PNP_EVENT FilterNetPnPEvent;
extern FILTER_STATUS FilterStatus;


